version: '3'

services:

  app:
    build: .
    container_name: app
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    # extra_hosts:
    #   - "host.docker.internal:172.17.0.1"
    networks:
    - keycloak-network

networks:
  keycloak-network:
    external: true
